swagger: "2.0"
info:
  version: "0.0.1"
  title: Todo API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /:
    get:
      description: "This endpoint returns all the todos available in the database"
      operationId: "GetAllTodos"
      parameters: []
      responses:
        200:
          description: "An array of todos"
          schema:
            type: "array"
            items: 
              $ref: "#/definitions/Todo"
    post: 
      description: "Add a new todo"
      operationId: "AddTodo"
      produces: 
      - "application/json"
      parameters: 
      - name: "todo"
        in: "body"
        description: "The todo to be added"
        required: true
        schema: 
          $ref: "#/definitions/Todo"
      responses: 
        200: 
          description: "Successful todo add"
      x-swagger-router-controller: 
        "AddTodo"
  /todo/{id}:
    get:
      description: "Retrieve a single todo by id"
      operationId: "FindTodoById"
      produces: 
      - "application/json"
      parameters: 
      - name: "id"
        in: "path"
        description: "Id of the todo to get"
        required: true
        type: "integer"
        format: "int64"
      responses: 
        200: 
          description: "Todo response"
          schema: 
            $ref: "#/definitions/Todo"
      x-swagger-router-controller: 
        "FindTodoById"
    delete: 
      description: "Delete a todo by id"
      operationId: "DeleteTodoById"
      parameters: 
      - name: "id"
        in: "path"
        description: "Id of the todo to delete"
        required: true
        type: "integer"
        format: "int64"
      responses: 
        204: 
          description: "Todo deleted"
      x-swagger-router-controller: 
        "DeleteTodoById"
    put: 
      description: "Update a single todo by id"
      operationId: "UpdateTodoById"
      parameters: 
      - name: "id"
        in: "path"
        description: "Id of the todo being updated"
        required: true
        type: "integer"
        format: "int64"
      - name: "updated_todo"
        in: "body"
        description: "The updated todo"
        required: true
        schema: 
          $ref: "#/definitions/Todo"
      responses: 
        200: 
          description: "Todo updated"
        400:
          description: "Yikes! An Error!"
      x-swagger-router-controller: 
        "DeleteTodoById"
  /swagger: 
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Todo:
    type: "object"
    properties:
      todo_id:
        type: "integer"
        description: "Id for the todo"
      todo:
        type: "string"
        description: "The todo item"
      datecreated:
        type: "string"
        format: "date-time"
        description: "Timestamp when the todo was created. Set by server"
      author:
        type: "string"
        description: "Creator of the todo"
      duedate:
        type: "string"
        format: "date-time"
        description: "When the todo is due"
      completed:
        type: "boolean"
        description: "Indicates if the todo was completed or not"
